seed: 42
n_rows: 10000
n_attrs: 60
n_informative: 24
n_label_attrs_tier0: 5
attribute:
  block_size: 6
  rho: 0.4
  positive_fraction: 0.5
  scale_low: 0.6
  scale_high: 2.5
  lognormal_scale_low: 0.7
  lognormal_scale_high: 1.3
  lognormal_shift_mean: 0.25
  lognormal_shift_std: 0.15
  distractor_rho: 0.2
  distractor_scale_low: 0.5
  distractor_scale_high: 3.0
  heavy_tail_fraction: 0.35
  heavy_tail_df: 3.0
n_true_features:
  tier1: 20
  tier2: 20
  tier3: 20
  tier4: 15
positive_rate: 0.10
sigma_logit: 0.5
val_frac: 0.20
xgb:
  tree_method: hist
  max_bin: 256
  max_depth: 6
  min_child_weight_range: [1.0, 20.0]
  learning_rate_range: [0.01, 0.2]
  subsample_range: [0.6, 1.0]
  colsample_bytree_range: [0.6, 1.0]
  reg_alpha_range: [1.0e-8, 10.0]
  reg_lambda_range: [1.0e-8, 10.0]
  scale_pos_weight: 2.0
  early_stopping_rounds: 100
optuna:
  n_trials: 10
  timeout_seconds: 300
