seed: 42
n_rows: 10000
n_attrs: 60
n_informative: 24
n_label_attrs_tier0: 5
n_true_features:
  tier1: 20
  tier2: 20
  tier3: 20
positive_rate: 0.10
sigma_logit: 0.5
val_frac: 0.20
xgb:
  tree_method: hist
  max_bin: 256
  max_depth: 6
  min_child_weight_range: [1.0, 20.0]
  learning_rate_range: [0.01, 0.2]
  subsample_range: [0.6, 1.0]
  colsample_bytree_range: [0.6, 1.0]
  reg_alpha_range: [1.0e-8, 10.0]
  reg_lambda_range: [1.0e-8, 10.0]
  scale_pos_weight: 2.0
  early_stopping_rounds: 100
optuna:
  n_trials: 10
  timeout_seconds: 300
